SELECT * FROM CUSTOMER
SELECT * FROM CATEGORY
SELECT * FROM PRODUCT
SELECT * FROM ORDERS


------------------------------SUB QUERY AND JOINS FOR ASSIGNMENT TABLES---------------------------------

--1	LIST COSTLIEST PRODUCT DETAILS
SELECT * FROM PRODUCT WHERE PRICE IN (SELECT MAX(PRICE) FROM PRODUCT)

--2	PRINT ALL THE ORDERS PLACED BY CUSTOMER AJAY
SELECT * FROM ORDERS WHERE CUST_ID IN (SELECT CUST_ID FROM CUSTOMER WHERE CUST_NAME='AJAY')

--3	LIST PRODUCTNAME, PRICE, QUANTITY AND CATEGORYNAME
SELECT P.PROD_NAME, P.PRICE, P.QUANTITY, CAT.CAT_NAME FROM PRODUCT P JOIN CATEGORY CAT ON P.CAT_ID=CAT.CAT_ID

--4	LIST ORDERYEAR, ORDERMONTH, ORDERID, ORDERDATE, CUSTOMERNAME FOR ALL ORDERS
SELECT O.OD_YEAR, O.OD_MONTH, O.OD_ID, O.OD_DATE, CT.CUST_NAME FROM ORDERS O LEFT JOIN CUSTOMER CT ON O.CUST_ID=CT.CUST_ID

--5	LIST ALL THE ORDERS FOR THE CATEGORY ELECTRONICS
SELECT * FROM ORDERS WHERE PROD_ID IN (SELECT PROD_ID FROM PRODUCT WHERE CAT_ID IN (SELECT CAT_ID FROM CATEGORY WHERE CAT_NAME='ELECTRONICS'))

--6	LIST ALL THE ORDERS WHOSE PRICE IS GREATER THEN 1000

--7	LIST ALL THE ORDERS FOR THE CUSTOMER CHIRAG PLACED FOR CATEGORY FOOD


--8	LIST ORDERYEAR, ORDERMONTH, ORDERID, ORDERDATE, CUSTOMERNAME, 
--	CATEGORYNAME, PRODUCTNAME, PRICE, ORDERQTY, TOTAL(PRICE*ORDERQTY) FOR ALL ORDERS


--9	LIST TOTAL ORDERCOUNT, TOTALORDERQTY, TOTALVALUE OF ORDERS PLACE BY CUSTOMER AJAY

--	HINT: BELOW OUTPUT
--ORDERCOUNT	TOTALORDERQTY	TOTALVALUE
--3					9				620.00



--10	LIST SUM OF  ORDERQTY  FROM ORDERS TABLE FOR CATEGORY ELECTRONICS 

--HINT
--TOTALORDERQTY
--2



--11	PRINT RECORD OF 3RD HIGHEST SALARY EARNED EMPLOYEE  (DO NOT USE TOP N)



