---------------------------------FUNCTIONS

--1. TAKE PRODUCTNAME AS PARAMETER AND RETURN UNITPRICE

--2. TAKE PRODUCTNAME AS PARAMETER AND RETURN UNITSINSTOCK AND 
--UNINTSONORDER

--3. TAKE POSTALCODE AS PARAMETER AND RETURN CUSTOMER NAME. IF POSTAL CODE IS 
--NOT VALID DISPLAY ERROR MESSAGE

--4. TAKE COUNTRY AS PARAMETER AND RETURN CITY AND POSTALCODE FOR A 
--CUSTOMERS

--5. TAKE EMPLOYEE FIRSTNAME AND LASTNAME AS PARAMETER AND RETURN ALL 
--CUSTOMERS COMPANY NAME, CONTACTNAME, CONTACTTILE

--6. TAKE YEAR AND EMPLOYEENAME AND DISPLAY AMOUNT OF ORDERS HANDLE BY THE 
--EMPLOYEE IN A YEAR (SUM OF QUANTITY)

--7. TAKE YEAR AND MONTH AS PARAMETER AND RETURN NO OF ORDERS SHIPPED IN THE 
--GIVEN MONTH

--8. TAKE PRODUCTNAME AS PARAMTER AND RETURN TOTLA UNITS OF ORDER PLACED FOR 
--THE PRODUCT (SUM(ORDERED QUANTITY)
--Hint: use Products and [Order Details] table

--9. TAKE ORDERID AS PARAMETER AND RETURN TOTAL UNITS OF ORDER PLACE FOR THE 
--ORDERID