CREATE DATABASE TRAINING;

use training;

Declare @Cname char(20)
Declare @Vname varchar(20)

set @Cname='Himan'
set @Vname='Himan'

print Datalength(@Cname) --20
print Datalength(@Vname) --5

Declare @NCname nchar(20)
Declare @NVname nvarchar(20)

set @NCname='Himanshugupta'
set @NVname='Himanshugupta'

print Datalength(@NCname) --40
print Datalength(@NVname) --10

print @CName
print @NVName

Select Getdate()

DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT(
	DEPTNO NUMERIC(3) NOT NULL PRIMARY KEY,
	DEPTNAME VARCHAR(20) NOT NULL UNIQUE
);


--IDENTITY(START VALUE, INCREMENT KEY) -> AUTO INCREAMENT COLUMN VALUE

CREATE TABLE EMPLOYEE(
	EMPNO NUMERIC(4) IDENTITY(1,1) NOT NULL PRIMARY KEY,
	EMPNAME VARCHAR(20) NOT NULL,
	DESIG VARCHAR(20) NULL,
	HIREDATE DATETIME NULL DEFAULT GETDATE(),
	MGR NUMERIC(4) NULL REFERENCES EMPLOYEE(EMPNO),
	SALARY NUMERIC(10,2) NULL CHECK (SALARY >=5000),
	DEPTNO NUMERIC(3) NULL REFERENCES DEPARTMENT(DEPTNO)  
);

INSERT INTO DEPARTMENT VALUES(10, 'HR')
INSERT INTO DEPARTMENT VALUES(20, 'DEVELOPER')

INSERT INTO EMPLOYEE VALUES('hIMANSHU','CEO','06/04/2021',NULL,20000,NULL)
INSERT INTO EMPLOYEE(EMPNAME,DEPTNO) VALUES('RAGHU',10)
INSERT INTO EMPLOYEE(EMPNAME,DESIG,DEPTNO) VALUES('HANNI','DEVELOPER',20)

INSERT INTO EMPLOYEE(EMPNAME,DEPTNO) VALUES('PRIYA',20)

SELECT * FROM EMPLOYEE WHERE EMPNAME='PRIYA'
UPDATE EMPLOYEE SET DESIG='DEVELOPER', SALARY=125000, HIREDATE='06/01/2021' WHERE EMPNO=1

SELECT * FROM DEPARTMENT

SELECT * FROM EMPLOYEE;

 SP_HELP 'DEPARTMENT' -- gives all details about the table

SP_HELP 'EMPLOYEE'

DELETE FROM EMPLOYEE WHERE EMPNO=3

ALTER TABLE EMPLOYEE ADD GENDER CHAR(1) NULL

--UPDATE EMPLOYEE SET GENDER = 'F' WHERE EMPNAME='PRIYA';

--UPDATE EMPLOYEE SET GENDER = 'M' WHERE EMPNO=2 OR EMPNO=4

ALTER TABLE EMPLOYEE DROP COLUMN GENDER --ALTER TO DROP A COLUMN

ALTER TABLE EMPLOYEE ADD GENDER CHAR(1) NOT NULL DEFAULT 'NULL'

ALTER TABLE EMPLOYEE DROP CONSTRAINT DF__EMPLOYEE__GENDER__59FA5E80;


DELETE FROM DEPARTMENT WHERE DEPTNO=20 --ERROR

ALTER TABLE EMPLOYEE DROP CONSTRAINT FK__EMPLOYEE__DEPTNO__59063A47;

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK__EMPLOYEE__DEPTNO FOREIGN KEY (DEPTNO)
REFERENCES DEPARTMENT (DEPTNO) ON DELETE CASCADE --DELETE CASCADE PASS THE EFFECT TO ALL RELATED TABLES

INSERT INTO EMPLOYEE(EMPNAME, DEPTNO) VALUES('AMIT', 20)
INSERT INTO EMPLOYEE(EMPNAME, DEPTNO) VALUES('SWATI', 20)
INSERT INTO EMPLOYEE(EMPNAME, DEPTNO) VALUES('SANJAY', 10)
INSERT INTO EMPLOYEE(EMPNAME, DEPTNO) VALUES('AARTI', 10)
INSERT INTO EMPLOYEE(EMPNAME, DEPTNO) VALUES('BJ', 10)

DELETE FROM DEPARTMENT WHERE DEPTNO=20 

ALTER TABLE EMPLOYEE DROP CONSTRAINT FK__EMPLOYEE__DEPTNO

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK__EMPLOYEE__DEPTNO FOREIGN KEY (DEPTNO)
REFERENCES DEPARTMENT (DEPTNO) ON DELETE SET NULL --ON DELETE SET NULL

DELETE FROM DEPARTMENT WHERE DEPTNO=10

SELECT * FROM DEPARTMENT

SELECT * FROM EMPLOYEE;

INSERT INTO DEPARTMENT VALUES(10, 'HR')
INSERT INTO DEPARTMENT VALUES(20, 'DEVELOPER')

INSERT INTO EMPLOYEE(EMPNAME, DEPTNO) VALUES('AMIT', 20)
INSERT INTO EMPLOYEE(EMPNAME, DEPTNO) VALUES('SWATI', 20)
INSERT INTO EMPLOYEE(EMPNAME, DEPTNO) VALUES('SANJAY', 10)
INSERT INTO EMPLOYEE(EMPNAME, DEPTNO) VALUES('AARTI', 10)
INSERT INTO EMPLOYEE(EMPNAME, DEPTNO) VALUES('BJ', 10)

SELECT * FROM DEPARTMENT

SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE DROP CONSTRAINT FK__EMPLOYEE__DEPTNO

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK__EMPLOYEE__DEPTNO FOREIGN KEY (DEPTNO)
REFERENCES DEPARTMENT (DEPTNO) ON DELETE SET NULL ON UPDATE CASCADE --ON UPDATE CASCADE

UPDATE DEPARTMENT SET DEPTNO=100 WHERE DEPTNO=10;
UPDATE DEPARTMENT SET DEPTNO=1 WHERE DEPTNO=100;

--NO RULE
-- ON DELETE CASCADE
-- ON DELETE SET NULL (GOOD)
-- ON UPDATE CASCADE (GOOD)
-- ON UPDATE SET NULL

INSERT INTO DEPARTMENT VALUES(30, 'Designing')

DELETE FROM EMPLOYEE

ALTER TABLE EMPLOYEE DROP CONSTRAINT CK__EMPLOYEE__DESIG__5535A963;

INSERT INTO EMPLOYEE(EMPNAME,DESIG, DEPTNO) VALUES('BHAGYA','ARCHITECH', 30)
INSERT INTO EMPLOYEE(EMPNAME,DESIG, DEPTNO) VALUES('NATHU','DBA', 20)
INSERT INTO EMPLOYEE(EMPNAME,DESIG, DEPTNO) VALUES('SONU','DEVELOPER', 1)
INSERT INTO EMPLOYEE(EMPNAME,DESIG, DEPTNO) VALUES('NATHU','DEVELOPER', 1)
INSERT INTO EMPLOYEE(EMPNAME,DESIG, DEPTNO) VALUES('NATHU','DEVELOPER', 1)

SELECT * FROM DEPARTMENT

SELECT * FROM EMPLOYEE;

CREATE TABLE PROJECT(
	PROJ_ID INT NOT NULL PRIMARY KEY,
	PROJ_NAME VARCHAR(20) UNIQUE
)

CREATE TABLE EMP_PROJECT_DETAIL(
	EMPNO NUMERIC(4) NOT NULL REFERENCES EMPLOYEE(EMPNO),
	PROJ_ID INT NOT NULL REFERENCES PROJECT(PROJ_ID),
	HRS INT,
	RATE NUMERIC(10,2),
	PRIMARY KEY(EMPNO, PROJ_ID)
)

--CREATING NEW SCHEMA
CREATE SCHEMA HR

DROP TABLE HR.EMPLOYEE;
DROP TABLE HR.DEPARTMENT;

CREATE TABLE HR.DEPARTMENT(
	DEPTNO NUMERIC(3) NOT NULL PRIMARY KEY,
	DEPTNAME VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE HR.EMPLOYEE(
	EMPNO NUMERIC(4) IDENTITY(1,1) NOT NULL PRIMARY KEY,
	EMPNAME VARCHAR(20) NOT NULL,
	DESIG VARCHAR(20) NULL,
	HIREDATE DATETIME NULL DEFAULT GETDATE(),
	MGR NUMERIC(4) NULL REFERENCES EMPLOYEE(EMPNO),
	SALARY NUMERIC(10,2) NULL CHECK (SALARY >=5000),
	DEPTNO NUMERIC(3) NULL REFERENCES DEPARTMENT(DEPTNO)  
);

SELECT * FROM DEPARTMENT

SELECT * FROM HR.DEPARTMENT