//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LINQAssignmentEntities : DbContext
    {
        public LINQAssignmentEntities()
            : base("name=LINQAssignmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPT> DEPTs { get; set; }
        public virtual DbSet<EMP> EMPs { get; set; }
    
        public virtual int JobWiseDetails(string job, ObjectParameter totalEmp, ObjectParameter maxSal, ObjectParameter minSal)
        {
            var jobParameter = job != null ?
                new ObjectParameter("job", job) :
                new ObjectParameter("job", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("JobWiseDetails", jobParameter, totalEmp, maxSal, minSal);
        }
    }
}
